#!/usr/bin/env bash
# Install the Mellonta Linux client and save launchers for one Raft home.
set -Eeuo pipefail

usage() {
  cat <<'EOF'
Usage: bash setup-client.sh --server-url URL --workspace SLUG [options]

Installs the latest published Mellonta Linux x86-64 release, then logs in,
attaches to your workspace, and starts Computer. Run as your agent user, without
sudo. Node, npm, Docker, and a source checkout are not required.

--server-url URL     Your Raft portal origin, e.g. http://a.b.com:8080.
--workspace SLUG     Workspace slug from the portal URL, with or without /.
--home PATH          Client state (default RAFT_HOME, SLOCK_HOME, then ~/.slock).
--install-dir PATH   Binary directory (default RAFT_COMPUTER_INSTALL_DIR, an
                     existing <home>/bin installation, then ~/.local/bin).
--version VERSION    Install an exact X.Y.Z-mellonta.N release instead of latest.
--reset              Delete ALL state in the selected home after installation
                     succeeds and Computer stops. No backup or migration is kept.
--install-only       Install and write launchers; leave Computer stopped. Use
                     this without a terminal, then run the saved connect.sh.
--help               Show this help.

Launchers are written to <home>/mellonta/. Shell startup files are not changed.
Install and authenticate your agent runtime (e.g. Claude Code or Codex) separately.
EOF
}

fail() { printf 'ERROR: %s\n' "$*" >&2; exit 1; }
log() { printf '\n[raft-client-setup] %s\n' "$*"; }

expand_home() {
  case "$1" in
    '~') printf '%s\n' "$HOME" ;;
    '~/'*) printf '%s/%s\n' "$HOME" "${1#\~/}" ;;
    *) printf '%s\n' "$1" ;;
  esac
}

check_reset_home() {
  case "$state_home" in
    /|/data|/home|/root|/tmp|/var|/opt|/usr|/srv|/mnt|/media|"$(realpath -m -- "$HOME")"|"$(realpath -m -- "$HOME/.local/bin")")
      fail "Refusing to reset a general-purpose directory: $state_home" ;;
  esac
  case "$(pwd -P)/" in
    "$state_home/"*) fail "Run setup from outside the state directory being reset." ;;
  esac
  if [[ -d "$state_home" && -n "$(ls -A -- "$state_home")" ]]; then
    [[ -d "$state_home/computer" && ! -L "$state_home/computer" ]] ||
      fail "Refusing to reset a nonempty directory without Computer state: $state_home"
  fi
}

assert_stopped() {
  local path pid
  for path in computer/run/service.pid computer/service.pid computer/supervisor.pid; do
    [[ -f "$state_home/$path" ]] || continue
    pid=$(cat -- "$state_home/$path")
    if [[ "$pid" =~ ^[0-9]+$ ]] && (( pid > 1 )) && kill -0 "$pid" 2>/dev/null; then
      fail "Computer PID $pid is still running in $state_home; state has not been erased."
    fi
  done
}

write_launchers() {
  local config="$state_home/mellonta"
  mkdir -p -- "$config"
  {
    printf '# Generated by setup-client.sh. Rerun setup to change these paths.\n'
    printf 'export RAFT_HOME=%q\nexport SLOCK_HOME=%q\n' "$state_home" "$state_home"
    printf 'export RAFT_COMPUTER_INSTALL_DIR=%q\n' "$install_dir"
    printf 'export PATH=%q:"$PATH"\n' "$install_dir"
    printf 'export RAFT_COMPUTER_RELEASE_BACKEND=legacy-cdn\n'
    printf 'export RAFT_COMPUTER_RELEASE_BASE=%q\n' "$release_base"
    printf 'export RAFT_COMPUTER_UPGRADE_BASE_URL=%q\n' "$release_base"
  } > "$config/runtime.sh"
  {
    printf '#!/usr/bin/env bash\nset -Eeuo pipefail\n'
    printf 'source %q\n' "$config/runtime.sh"
    printf 'exec %q "$@"\n' "$install_dir/raft-computer"
  } > "$config/raft-computer"
  {
    printf '#!/usr/bin/env bash\nset -Eeuo pipefail\n'
    printf 'exec bash %q setup %q --server-url %q "$@"\n' "$config/raft-computer" "/$workspace" "$server_url"
  } > "$config/connect.sh"
  {
    printf '#!/usr/bin/env bash\nset -Eeuo pipefail\n'
    printf 'exec bash %q start %q "$@"\n' "$config/raft-computer" "/$workspace"
  } > "$config/start.sh"
  chmod 700 "$config/runtime.sh" "$config/raft-computer" "$config/connect.sh" "$config/start.sh"
}

main() {
  local server_url='' workspace='' version='' reset=0 install_only=0 option
  local state_home="${RAFT_HOME:-${SLOCK_HOME:-$HOME/.slock}}"
  local install_dir="${RAFT_COMPUTER_INSTALL_DIR:-}"
  local release_base='https://github.com/Mellonta/raft-source/releases/download'
  while (( $# )); do
    option=$1
    case "$option" in
      --server-url|--workspace|--home|--install-dir|--version)
        (( $# >= 2 )) && [[ -n "$2" && "$2" != --* ]] || fail "$option requires a value."
        case "$option" in
          --server-url) server_url=$2 ;; --workspace) workspace=${2#/} ;;
          --home) state_home=$2 ;; --install-dir) install_dir=$2 ;; --version) version=$2 ;;
        esac
        shift 2 ;;
      --reset) reset=1; shift ;;
      --install-only) install_only=1; shift ;;
      --help|-h) usage; return ;;
      *) fail "Unknown option: $option" ;;
    esac
  done
  [[ "$server_url" =~ ^https?://[^/?#@[:space:]]+/?$ ]] || fail "--server-url must be an http(s) origin, e.g. http://a.b.com:8080."
  server_url=${server_url%/}
  [[ "$workspace" =~ ^[a-zA-Z0-9][a-zA-Z0-9_-]*$ ]] || fail "--workspace must be the workspace slug from your portal URL, not a URL or UUID."
  [[ "$(uname -s)" == Linux && "$(uname -m)" == x86_64 ]] || fail "The published Mellonta client supports Linux x86-64 only."
  if (( ! install_only )) && [[ ! -t 0 || ! -t 1 ]]; then
    fail "Login needs an interactive terminal. Use --install-only, then run the saved connect.sh in a terminal."
  fi
  local tool
  for tool in curl sha256sum realpath awk mktemp ps; do
    command -v "$tool" >/dev/null || fail "Missing $tool. On Ubuntu, install curl ca-certificates coreutils gawk procps."
  done
  umask 077
  state_home=$(expand_home "$state_home")
  [[ ! -L "${state_home%/}" ]] || fail "Pass the real state directory, not a symlink: $state_home"
  state_home=$(realpath -m -- "$state_home")
  [[ ! -e "$state_home" || ( -d "$state_home" && -O "$state_home" ) ]] || fail "State must be a directory owned by the current user: $state_home"
  if [[ -z "$install_dir" ]]; then
    if [[ -x "$state_home/bin/raft-computer" ]]; then install_dir="$state_home/bin";
    else install_dir="$HOME/.local/bin"; fi
  fi
  install_dir=$(realpath -m -- "$(expand_home "$install_dir")")
  if (( reset )); then check_reset_home; fi

  local latest_url expected actual old_binary=''
  if [[ -z "$version" ]]; then
    latest_url=$(curl --proto '=https' --proto-redir '=https' -fsSIL --retry 3 --connect-timeout 15 --max-time 90 \
      -o /dev/null -w '%{url_effective}' https://github.com/Mellonta/raft-source/releases/latest)
    [[ "$latest_url" == https://github.com/Mellonta/raft-source/releases/tag/* ]] || fail "Could not resolve the fork's latest published release."
    version=${latest_url##*/}
  fi
  [[ "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+-mellonta\.[0-9]+$ ]] || fail "Expected a Mellonta release version; got $version."
  log "Installing $version from Mellonta/raft-source into $install_dir; state: $state_home"
  # Keep the temporary files outside the home that --reset can delete.
  client_setup_tmp=$(mktemp -d /tmp/raft-client-setup.XXXXXXXX)
  trap 'rm -rf -- "$client_setup_tmp"' EXIT
  for asset in install.sh SHA256SUMS; do
    curl --proto '=https' --proto-redir '=https' -fsSL --retry 3 --connect-timeout 15 --max-time 120 \
      "$release_base/$version/$asset" -o "$client_setup_tmp/$asset"
  done
  expected=$(awk '$2 == "install.sh" { print $1 }' "$client_setup_tmp/SHA256SUMS")
  [[ "$expected" =~ ^[0-9a-f]{64}$ ]] || fail "Release has no unique installer checksum."
  actual=$(sha256sum "$client_setup_tmp/install.sh")
  [[ "${actual%% *}" == "$expected" ]] || fail "Installer checksum mismatch; nothing has been stopped or erased."

  export RAFT_HOME="$state_home" SLOCK_HOME="$state_home"
  export RAFT_COMPUTER_RELEASE_BACKEND=legacy-cdn
  export RAFT_COMPUTER_RELEASE_BASE="$release_base" RAFT_COMPUTER_UPGRADE_BASE_URL="$release_base"
  export RAFT_COMPUTER_VERSION="$version" RAFT_COMPUTER_INSTALL_CHANNEL="pinned:$version"
  export RAFT_COMPUTER_INSTALL_DIR="$install_dir" RAFT_COMPUTER_FORCE=1 RAFT_COMPUTER_NO_MODIFY_PATH=1
  if [[ -d "$state_home/computer" ]]; then
    for old_binary in "$install_dir/raft-computer" "$state_home/bin/raft-computer" "$(command -v raft-computer || true)"; do
      [[ -x "$old_binary" ]] && break
    done
    [[ -x "$old_binary" ]] || fail "Existing Computer state found, but no binary. Pass --install-dir pointing to the old raft-computer binary's directory."
    log 'Stopping the existing Computer before replacement.'
    "$old_binary" stop
    assert_stopped
  fi
  # Use the release installer for binary/WASM verification and K updater cleanup.
  # A failed download does not erase the existing home.
  sh "$client_setup_tmp/install.sh" --version "$version" --channel "pinned:$version"
  "$install_dir/raft-computer" stop
  assert_stopped

  if (( reset )); then
    check_reset_home
    # The portal's installer can put its binary INSIDE the state home. Preserve
    # only the newly verified executable and WASM, never old state or credentials.
    cp -- "$install_dir/raft-computer" "$install_dir/photon_rs_bg.wasm" "$client_setup_tmp/"
    log "Deleting client state in $state_home (no backup)."
    rm -rf -- "$state_home"
    mkdir -p -- "$install_dir"
    install -m 755 "$client_setup_tmp/raft-computer" "$install_dir/raft-computer"
    install -m 644 "$client_setup_tmp/photon_rs_bg.wasm" "$install_dir/photon_rs_bg.wasm"
  fi
  mkdir -p -- "$state_home/computer"
  printf 'pinned:%s\n' "$version" > "$state_home/computer/channel"
  write_launchers
  log "Installed $version and pinned updates to that release."
  printf 'Connect: bash %q\nStart:   bash %q\nStatus:  bash %q status\nLogs:    %s/computer/run/service.log\n' \
    "$state_home/mellonta/connect.sh" "$state_home/mellonta/start.sh" "$state_home/mellonta/raft-computer" "$state_home"
  if (( ! install_only )); then bash "$state_home/mellonta/connect.sh"; fi
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then main "$@"; fi
