#!/usr/bin/env bash
# Bootstrap this fork on Ubuntu. Docker must already be installed and accessible.
# Run as the account that will own Raft; sudo is used only for apt and directories.
set -Eeuo pipefail

usage() {
  cat <<'EOF'
Usage: bash setup-ubuntu.sh [--allowed-hosts HOSTS] [--name NAME] [--no-start] [--update]

Source: /data/raft                 Fork: https://github.com/Mellonta/raft-source.git
State:  /data/.raftdev             Agent home: /data/.raft
Config/launchers: /data/.raft-config
New nvm installation: /data/.nvm   Caches/temp: /data/.cache, .npm, .pnpm-store, .tmp

--allowed-hosts HOSTS  Comma-separated web hostnames (without scheme or port).
--name NAME           Environment name; default raft (reuse the same name later).
--no-start            Install and configure without launching services.
--update              Fast-forward an existing clean checkout before setup.
--help                Show this help without making changes.

Docker configuration, storage, group membership, and services are not modified.
An existing nvm installation is reused. Node and pnpm versions come from the repo.
Existing runtime settings are preserved; --allowed-hosts explicitly updates that setting.
EOF
}

fail() { printf 'ERROR: %s\n' "$*" >&2; return 1; }
log() { printf '\n[raft-setup] %s\n' "$*"; }

ensure_directory() {
  local directory=$1
  if [[ ! -d "$directory" ]]; then
    "${elevate[@]}" install -d -m 0700 -o "$(id -u)" -g "$(id -g)" "$directory"
  fi
  [[ -w "$directory" && -x "$directory" ]] || fail "Directory is not writable by $(id -un): $directory"
}

prepare_checkout() {
  local source_dir=$1 update=$2
  if [[ -d "$source_dir/.git" ]]; then
    [[ "$(git -C "$source_dir" rev-parse --show-toplevel)" == "$source_dir" ]] || fail "Not the expected checkout: $source_dir"
    local origin
    origin=$(git -C "$source_dir" remote get-url origin)
    case "$origin" in
      https://github.com/Mellonta/raft-source.git|https://github.com/Mellonta/raft-source|git@github.com:Mellonta/raft-source.git) ;;
      *) fail "Existing checkout has a different origin: $origin"; return 1 ;;
    esac
    if [[ "$update" == 1 ]]; then
      [[ -z "$(git -C "$source_dir" status --porcelain)" ]] || fail "Checkout has local changes; refusing --update."
      [[ "$(git -C "$source_dir" branch --show-current)" == main ]] || fail "--update requires the main branch."
      git -C "$source_dir" pull --ff-only origin main
    fi
  elif [[ -e "$source_dir" && -n "$(ls -A "$source_dir")" ]]; then
    fail "$source_dir is nonempty and is not the fork checkout."
  else
    git clone --branch main https://github.com/Mellonta/raft-source.git "$source_dir"
  fi
  [[ -f "$source_dir/scripts/dev/raftdev-paths.ts" ]] || fail "Checkout is too old for external state; update it first."
}

write_runtime_files() {
  local config_dir=$1 source_dir=$2 data_dir=$3 node_bin=$4 nvm_dir=$5 environment=$6 hosts_set=$7 hosts=$8
  local settings="$config_dir/settings.sh"
  local runtime="$config_dir/runtime.sh"
  if [[ ! -e "$settings" ]]; then
    cat > "$settings" <<'EOF'
# Local overrides. Setup preserves this file on reruns.
export SLOCKDEV_TUNNEL=0
export SLOCKDEV_IDLE_TTL_SECONDS=0
export SLOCKDEV_TRACE_WORKER=0
export SLOCKDEV_TRACE_OBSERVE=0
export SLOCKDEV_TRACE_WORKER_URL=''
export SLOCKDEV_API_LATENCY_MS=''
export RAFTDEV_COMPUTER=1
EOF
    printf '[[ ${VITE_DEV_ALLOWED_HOSTS+x} ]] || export VITE_DEV_ALLOWED_HOSTS=%q\n' "$hosts" >> "$settings"
  elif [[ "$hosts_set" == 1 ]]; then
    python3 - "$settings" "$hosts" <<'PY'
import pathlib, shlex, sys
file = pathlib.Path(sys.argv[1])
lines = [line for line in file.read_text().splitlines() if not line.startswith("[[ ${VITE_DEV_ALLOWED_HOSTS+x} ]] || export VITE_DEV_ALLOWED_HOSTS=")]
lines.append("[[ ${VITE_DEV_ALLOWED_HOSTS+x} ]] || export VITE_DEV_ALLOWED_HOSTS=" + shlex.quote(sys.argv[2]))
file.write_text("\n".join(lines) + "\n")
PY
  fi
  {
    printf '# Generated by setup-ubuntu.sh; put overrides in settings.sh.\n'
    printf 'export NVM_DIR=%q\n' "$nvm_dir"
    printf 'export RAFTDEV_STATE_DIR=%q\n' "$data_dir/.raftdev"
    printf 'export RAFTDEV_PERSISTENT_DATA=1\n'
    printf 'export SLOCKDEV_HOME=%q\n' "$data_dir/.raft"
    printf 'export SLOCK_HOME=%q\n' "$data_dir/.raft"
    printf 'export RAFT_HOME=%q\n' "$data_dir/.raft"
    printf 'export npm_config_cache=%q\n' "$data_dir/.npm"
    printf 'export npm_config_store_dir=%q\n' "$data_dir/.pnpm-store"
    printf 'export PNPM_HOME=%q\n' "$data_dir/.pnpm"
    printf 'export XDG_CACHE_HOME=%q\n' "$data_dir/.cache"
    printf 'export VITE_DEV_CACHE_DIR=%q\n' "$data_dir/.cache/raft-vite"
    printf 'export TMPDIR=%q\n' "$data_dir/.tmp"
    printf 'export SHELL=/bin/bash\n'
    printf 'export RAFTDEV_SHELL_INIT=%q\n' "$runtime"
    printf 'export PATH=%q:%q:"$PATH"\n' "$node_bin" "$data_dir/.pnpm"
    printf 'source %q\n' "$settings"
  } > "$runtime"
  {
    printf '#!/usr/bin/env bash\nset -euo pipefail\numask 077\n'
    printf 'source %q\ncd %q\n' "$runtime" "$source_dir"
    printf 'exec ./raftdev "$@"\n'
  } > "$config_dir/raftdev"
  {
    printf '#!/usr/bin/env bash\nset -euo pipefail\numask 077\n'
    printf 'exec %q start %q "$@"\n' "$config_dir/raftdev" "$environment"
  } > "$config_dir/start.sh"
  chmod 0600 "$settings" "$runtime"
  chmod 0700 "$config_dir/raftdev" "$config_dir/start.sh"
}

main() {
  local data_dir=/data source_dir=/data/raft config_dir=/data/.raft-config
  local environment=raft hosts="${VITE_DEV_ALLOWED_HOSTS:-}" hosts_set=0 start=1 update=0
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --allowed-hosts|--name)
        [[ $# -ge 2 && "$2" != --* ]] || fail "$1 requires a value."
        if [[ "$1" == --allowed-hosts ]]; then hosts=$2; hosts_set=1; else environment=$2; fi
        shift 2 ;;
      --no-start) start=0; shift ;;
      --update) update=1; shift ;;
      -h|--help) usage; return ;;
      *) fail "Unknown option: $1"; return 1 ;;
    esac
  done
  [[ "$environment" =~ ^[A-Za-z0-9._-]{1,128}$ && "$environment" != . && "$environment" != .. ]] || fail "Invalid environment name."
  [[ "$(uname -s)" == Linux ]] || fail "This script is for Ubuntu, not this operating system."
  local ID VERSION_ID
  source /etc/os-release
  [[ "$ID" == ubuntu ]] || fail "This script requires Ubuntu."
  local -a elevate=()
  if [[ $EUID -ne 0 ]]; then
    command -v sudo >/dev/null || fail "sudo is required to install missing Ubuntu packages."
    elevate=(sudo)
  fi
  # Check the user's existing Docker access, without sudo or daemon mutations.
  command -v docker >/dev/null || fail "Docker must already be installed."
  local docker_root
  docker_root=$(docker info --format '{{.DockerRootDir}}') || fail "Docker is not accessible to this account; use the account with working Docker access."
  log "Using existing Docker storage: $docker_root (unchanged)"
  [[ -d "$data_dir" && ! -L "$data_dir" ]] && mountpoint -q "$data_dir" || fail "Mount your data disk at /data before running setup."
  local -a missing=()
  local package
  for package in ca-certificates curl git tmux lsof build-essential python3 pkg-config; do
    [[ "$(dpkg-query -W -f='${Status}' "$package" 2>/dev/null || true)" == 'install ok installed' ]] || missing+=("$package")
  done
  if [[ ${#missing[@]} -gt 0 ]]; then
    log "Installing missing Ubuntu prerequisites: ${missing[*]}"
    "${elevate[@]}" apt-get update
    "${elevate[@]}" env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends "${missing[@]}"
  fi
  umask 077
  ensure_directory "$source_dir"
  for package in .raft-config .raftdev .raft .npm .pnpm .pnpm-store .cache .tmp; do
    ensure_directory "$data_dir/$package"
  done
  log 'Preparing the source checkout'
  prepare_checkout "$source_dir" "$update"
  # Refuse an implicit migration of an existing in-checkout deployment.
  if [[ -s "$source_dir/.dev-env-$environment.json" || -d "$source_dir/.slockdev/$environment" ]]; then
    fail "Existing in-checkout state for '$environment' needs migration to /data/.raftdev before this setup can switch paths. It has not been moved or deleted."
  fi
  local nvm_dir="${NVM_DIR:-}"
  if [[ ! -s "$nvm_dir/nvm.sh" ]]; then
    if [[ -s /data/.nvm/nvm.sh ]]; then nvm_dir=/data/.nvm
    elif [[ -s "$HOME/.nvm/nvm.sh" ]]; then nvm_dir="$HOME/.nvm"
    else nvm_dir=/data/.nvm
    fi
  fi
  export NVM_DIR="$nvm_dir" npm_config_cache="$data_dir/.npm" TMPDIR="$data_dir/.tmp"
  if [[ ! -s "$NVM_DIR/nvm.sh" ]]; then
    ensure_directory "$NVM_DIR"
    log 'Installing nvm v0.40.8'
    local installer
    installer=$(mktemp "$TMPDIR/nvm-install.XXXXXX")
    curl -fsSL --retry 3 https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.8/install.sh -o "$installer"
    PROFILE=/dev/null bash "$installer"
    rm -f "$installer"
  fi
  local node_version pnpm_version
  node_version=$(tr -d '[:space:]' < "$source_dir/.node-version")
  [[ "$node_version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || fail 'Invalid Node pin in checkout.'
  log "Selecting Node $node_version (includes npm)"
  set +u
  source "$NVM_DIR/nvm.sh" --no-use
  nvm install "$node_version"
  nvm use --silent "$node_version"
  command -v npm >/dev/null || nvm install-latest-npm
  set -u
  command -v npm >/dev/null || fail 'npm is missing from the selected Node installation.'
  pnpm_version=$(node -p 'JSON.parse(require("fs").readFileSync(process.argv[1], "utf8")).packageManager' "$source_dir/package.json")
  [[ "$pnpm_version" =~ ^pnpm@[0-9]+\.[0-9]+\.[0-9]+$ ]] || fail 'Invalid pnpm pin in checkout.'
  if ! command -v pnpm >/dev/null || [[ "$(pnpm --version)" != "${pnpm_version#pnpm@}" ]]; then
    npm install --global "$pnpm_version"
  fi
  write_runtime_files "$config_dir" "$source_dir" "$data_dir" "$(dirname "$(command -v node)")" "$NVM_DIR" "$environment" "$hosts_set" "$hosts"
  if [[ "$hosts_set" == 1 ]]; then export VITE_DEV_ALLOWED_HOSTS="$hosts"; fi
  source "$config_dir/runtime.sh"
  log 'Installing server, web, and daemon dependencies'
  cd "$source_dir"
  pnpm --filter @botiverse/raft-server... --filter @botiverse/raft-web... --filter @botiverse/raft-daemon... install --frozen-lockfile --store-dir "$data_dir/.pnpm-store"
  log "Setup complete. Start with: bash $config_dir/start.sh"
  printf 'Settings: %s/settings.sh\nState: %s/.raftdev\nAgent home: %s/.raft\n' "$config_dir" "$data_dir" "$data_dir"
  if [[ "$start" == 1 ]]; then
    if tmux has-session -t "slock-$environment" 2>/dev/null; then
      log "Environment '$environment' already has a tmux session; leaving it running."
      "$config_dir/raftdev" status
    else
      bash "$config_dir/start.sh"
    fi
  fi
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then main "$@"; fi
